# Generated by Django 3.0.4 on 2020-04-26 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='User',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='coursestudent',
            old_name='Course',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='coursestudent',
            old_name='User',
            new_name='user',
        ),
    ]
