# Generated by Django 3.0.4 on 2020-04-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20200426_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursestudent',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
