# Generated by Django 3.0.4 on 2020-04-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_coursestudent_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursestudent',
            name='enabled',
        ),
        migrations.AddField(
            model_name='coursestudent',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
