# Generated by Django 3.0.4 on 2020-04-29 07:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20200427_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(verbose_name='Start at')),
                ('end_at', models.DateTimeField(verbose_name='End at')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Course')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.CourseStudent')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.AttendancePeriod')),
            ],
        ),
    ]
