# Generated by Django 3.0.4 on 2020-04-29 07:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20200429_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceperiod',
            name='start_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start at'),
        ),
    ]
